### PR TITLE
Remove read g4

### PR DESCRIPTION
**Pull request by zhut19**
The read g4 function can be in principle replaced by EPIX, however, it still would be nice to keep a read g4 function. This draft  PR is just trying to see removing the nestpy import can make the commits pass the Travis test again.

### CODE REVIEW

**Comment by zhut19** [comment]
@petergaemers hope you are okay with removing this read g4 part as epix is on the way. We can always add this back, but for now, nextpy is blocking the Travis check.

**Comment by petergaemers** [comment]
Yes of course. This function served mainly as a placeholder for EPIX

**Comment by jorana** [comment]
@zhut19 and @petergaemers , we solved the nestpy dep. in the base_env by downgrading to:
```nestpy==1.3.0     # WFsim dependency```
https://github.com/XENONnT/base_environment/pull/348

**Comment by zhut19** [comment]
Thanks @jorana, but I guess I pulled the trigger too soon. So now it is in the hand of EPIX.

**Pull request merged**
