### PR TITLE
Overwrite detector parameters with CMT

### PR DESCRIPTION
**Pull request by petergaemers**
Refactor parameters in order to stay compatible with the upcoming sims context: https://github.com/XENONnT/straxen/pull/555

### CODE REVIEW

**Comment by ramirezdiego** [comment]
That's all? From a chat with @l-althueser:
```
drift_time_gate -> electron_drift_time_gate
drift_velocity_liquid -> electron_drift_velocity
electron_lifetime_liquid -> elife
```

**Comment by petergaemers** [comment]
Is drift time gate in straxen?

**Comment by l-althueser** [comment]
Not yet in straxen but we want to have it there asap. (Maybe it is there and I missed it ..)

**Comment by jingqiangye** [comment]
@petergaemers @l-althueser The `electron_drift_time_gate` is in CMT, and also [in straxen](https://github.com/XENONnT/straxen/blob/master/straxen/plugins/event_processing.py#L330-L334) for a better `z_naive` [calculation](https://github.com/XENONnT/straxen/blob/master/straxen/plugins/event_processing.py#L406).

**Review by ramirezdiego — APPROVED** [review]
Hop! Thanks everyone.

**Pull request merged**
