### PR TITLE
Update Getting_started_wfsim.ipynb

### PR DESCRIPTION
**Pull request by GiovanniVolta**
Missing an s in wfsim.strax_interface.rand_instruction
https://github.com/XENONnT/WFSim/blob/a2707a8ac97bbe7b7f2f6cae979971743987318b/wfsim/strax_interface.py#L57

**What is the problem / what does the code in this PR do**

**WFSim needs you:**
 - Please add a test for this PR, as a bare minimum, make sure it's covered in coveralls!
 - Can you add a docsting to all your functions?

### CODE REVIEW

**Comment by ramirezdiego** [comment]
@GiovanniVolta Could you please also correct this guy (outdated file reference)
```
straxen.get_resource('https://raw.githubusercontent.com/XENONnT/'
                               'strax_auxiliary_files/master/fax_files/fax_config_nt.json',fmt='json').keys()
```
and give the notebook a run?

**Comment by GiovanniVolta** [comment]
@ramirezdiego sure, let me do it!

**Comment by petergaemers** [comment]
Thanks Giovanni.
Could you also change path_to_g4_file, path_to_config and path_to_nveto_config_file to strings?(Under the Geant4, Optical and nVeto headers) This is the reason why the readthedocs fails to include this notebook. Since they are not defined it crashes

**Comment by GiovanniVolta** [comment]
Everything should be fix now. Let me know if you spot anything wrong

**Comment by petergaemers** [comment]
The correct path to the configuration file is just "fax_config_nt_design.json". Like this it will fetch it from the database accesable from dali. Trying to get it directly from github might cause problems with either acces tokens or lack of internet connection

**Comment by GiovanniVolta** [comment]
> 
> 
> The correct path to the configuration file is just "fax_config_nt_design.json". Like this it will fetch it from the database accesable from dali. Trying to get it directly from github might cause problems with either acces tokens or lack of internet connection

Fix it!

**Review by petergaemers — APPROVED** [review]

**Pull request merged**
