### PR TITLE
S1 scintillation timing from NEST

### PR DESCRIPTION
**Pull request by terliuk**
**What is the problem / what does the code in this PR do**
Introduces new mode for S1 shape where timing is done from timing spline, and scintillation time is received directly from nestpy which will address issue #165

### CODE REVIEW

**Comment by terliuk** [comment]
here is the example of running it : https://github.com/XENONnT/analysiscode/blob/master/s1_pulse_shape/S1_WFsim_pulse_shape_NEST_example.ipynb

**Comment by skazama** [comment]
Hi @terliuk, I cannot comment about epix, but I had a look at your code and it looks fine. Also I managed to run the notebook with your branch and could generate Kr83m S1 signals without errors, so maybe we can merge this? (or do we have to wait for @ramirezdiego's ideas?)

**Comment by ramirezdiego** [comment]
Hi @skazama. The code works fine indeed (thanks for jumping in!), but in a recent chat with @terliuk I suggested that it would be better to push the relevant changes to epix before merging this PR; i.e., to output the required information in the instructions (efield, number of excitons...).

This requires to change the instructions format also in WFSim: either by adding another one, with these extra columns, or adding the columns to the default one, but make epix always print out some dummy number for them. In case this wasn't clear: epix reads the format directly from WFSim: https://github.com/XENONnT/epix/blob/43e7e31a05d0ff52863c2017f367bff7eb859312/epix/io.py#L202 This would be the missing part of this PR.

**Comment by terliuk** [comment]
after recent changes, i need to do extensive testing again, confirming that it works as intended

**Review by zhut19 — APPROVED** [review]

**Pull request merged**
