### PR TITLE
add h-diffusion function

### PR DESCRIPTION
**Pull request by zhut19**
We have been ignoring horizontal diffusion so far, which might impact the S2 pattern.

The added function in S2 pattern generation would now output diffused patterns, but with naive calculations

  - One can set an additional parameter `diffusion_constant_liquid_horizontal` in config to enable this
  - We will create updated xy positions for all electrons in each S2, the new pattern is calculated averaging over those new positions.
    - Positions outside the TPC radius will be ignored, as the output will be the average over all other positions.
    - It's not a weighted average, as an electron with 50 photon carries the same weight as an electron with 20 photon
    - There's no enforced time-positon correlation at this per electron level.

### CODE REVIEW

**Comment by zhut19** [comment]
It seems to be running fine

**Review by petergaemers — APPROVED** [review]

**Comment by terliuk** [comment]
Hi, I have a few comments:

1. How do we plan to control whether diffusion is applied? Do we just set diffusion to 0? (will it break in this case?)
2. Is it possible to set/overrride it using configuration and not editing fax file? 
3. (warning, taste opinion, we can ignore it for now) I don't like "diffusion_constant_liquid_horizontal" , prefer "diffusion_constant_transverse" and "diffusion_constant_longitudinal", as this is how it's referred in most of the literature.

**Comment by petergaemers** [comment]
Adding an "enable_horizontal_diffusion" flag to the config is a good idea

**Comment by ramirezdiego** [comment]
@zhut19 Since we're here, could you add docstrings for `s2_pattern_map_hdiff` and `photon_channels`?

**Comment by zhut19** [comment]
Thanks for the comments!
@terliuk and @petergaemers I hope this `getattr(self.config, 'diffusion_constant_transverse', 0) > 0` does the trick already. Both 0 or None will bypass the added function. A flag feels a bit redundant sometimes unless we try to track it.
@terliuk probably you already know this now, the `fax_config_override` does the trick.
@ramirezdiego you got it.

**Pull request merged**
