### PR TITLE
Seedopt

### PR DESCRIPTION
**Pull request by petergaemers**
This pull requests adds the option to set a seed for the random number generator.

### CODE REVIEW

**Comment by zhut19** [comment]
Cool, it would also be great if this seed can also be used for all those np.random in the core.py

**Comment by petergaemers** [comment]
Isn't setting the seed once enough?

According to this: https://stackoverflow.com/questions/59008887/what-is-the-working-range-of-numpy-random-seed
you set a global random state

**Comment by zhut19** [comment]
I see, setting it once does do the job. Although, `rand_instructions` is not always called (at least my habit is writing instructions to csv files first). Does it make more sense to move the seed setting to the setup in FaxSimulatorPlugin?

**Comment by petergaemers** [comment]
You are correct, let me fix that

**Pull request merged**
