### PR TITLE
Only nveto mc chain

### PR DESCRIPTION
**Pull request by mzks**
**What is the problem / what does the code in this PR do**
When there is only nVeto event in Geant4 file, for example, optical calibration, wfsim took errors related to epix.
This PR add treatments for that.
I added also treatments for epix https://github.com/XENONnT/epix/pull/36

### CODE REVIEW

**Comment by mzks** [comment]
Local test passed
```import strax, straxen, wfsim, epix
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import uproot
straxen.print_versions()
print('wfsim version:' + wfsim.__version__)
print('epix version:' + epix.__version__)

st = straxen.contexts.xenonnt_simulation()
st.register(wfsim.RawRecordsFromMcChain)
# To make correct lineage hash, set all parameters like `mc_chain`

epix_config = {
    'cut_by_eventid': True,         # means that entry_start and entry_stop refer to the original G4 event id
    'debug': True,                  # print runtime outputs
    'source_rate': 0,               # do not alter G4 time of events, because this will be done in WFSim
    'micro_separation_time': 10.,   # ns; default epix separation for clustering decision
    'max_delay': 1e7                # ns; default epix cut for long events (time wrt to first interaction in TPC)
}
epix_config['detector_config_override'] = None
epix_config['micro_separation'] = 0.05
epix_config['tag_cluster_by'] = 'time'
st.set_config(dict(
    detector='XENONnT',
    fax_file='/Users/mzks/xenon/mc/mc/workdir/laser_test1.root',
    #fax_file='/Users/mzks/xenon/WFSim/bench/tpc_and_nveto_cryoneutrons_200.root',
    event_rate=100.,
    chunk_size=5.,
    entry_start=0,
    entry_stop=20,
    fax_config='fax_config_nt_low_field.json',
    fax_config_override=dict(url_base='https://raw.githubusercontent.com/XENONnT/private_nt_aux_files/master/sim_files',
                             enable_electron_afterpulses=False),
    epix_config=epix_config,
    targets=('tpc',)))
# nVeto
st.set_config(dict(
    neutron_veto=True,
    fax_config_nveto='fax_config_nt_nveto.json',
    fax_config_override_nveto=dict(enable_noise=False,
                                   enable_pmt_afterpulses=False,
                                   enable_electron_afterpulses=False,
                                   pmt_transit_time_mean=46.0),
    targets=('tpc', 'nveto'),
))
st.set_config(dict(
    # gain_model_nv=("to_pe_constant", 0.01), override within xenonnt_simulation
    baseline_samples_nv=("nv_baseline_constant", 26, True), # Just a patch waiting for a decision in https://github.com/XENONnT/straxen/issues/478
))

run_id = 'mc_test_charm13'

rr_nv = st.get_array(run_id, 'raw_records_nv', progress_bar=False)
truth_nv = st.get_array(run_id, 'truth_nv', progress_bar=False)

print(truth_nv['g4id'])
print(rr_nv[0]['data'])
```

```
Simulating Raw Records: 100%|██████████| 20/20 [00:15<00:00,  1.25it/s]
Source finished!
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[12700 12700 12700 12700 12700 12700 12700 12700 12700 12700 12700 12700
 12700 12700 12700 12700 12700 12700 12700 12700 12700 12700 12700 12700
 12700 12700 12700 12901 12700 12700 12700 12097  3652     0  5461  8758
 10287 11293 11896 11254     0     0  2388  6802  9129 10332 11376 11857
 11937 11656 12419 12700 12419 12138 12419 12700 12419 12419 12700 12700
 12700 12700 12700 12700 12700 12700 12700 12700 12700 12700 12700 12700
 12700 12700 12700 12700 12700 12700 12700 12700 12700 12700 12700 12700
 12700 12700 12700 12700 12700     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0]
    ```

**Comment by mzks** [comment]
Better idea is on #191

**Comment by mzks** [comment]
We agree that wfsim itself should return empty array without options. reopen this and close #191

**Comment by mzks** [comment]
Test notebook

https://xe1t-wiki.lngs.infn.it/doku.php?id=xenon:xenonnt:mc:notes:nv_only_laser1

**Comment by zhut19** [comment]
Hi @mzks, sorry I wasn't looking into nveto things again. I guess this is finished right? Can I go ahead and merge it now?

**Comment by mzks** [comment]
@zhut19 Yes, we can go ahead except CodeFactor.

**Review by ramirezdiego — COMMENTED** [review]
@zhut19 Notice that we also merged here the Kr notebook that Keita was tracking for some reason...

**Comment by mzks** [comment]
@ramirezdiego It also requires to merge XENONnT/epix#36 for expected works.

**Comment by ramirezdiego** [comment]
@mzks Yes, that's correct. Notice that Daniel already dropped a review (which I agree with), requesting for changes.
Thank you for the fix here!

**Comment by petergaemers** [comment]
I still would like the krypton notebook to return.

**Pull request merged**
