### PR TITLE
Fix get_n_photons

### PR DESCRIPTION
**Pull request by HenningSE**
Looks like we missed to change `self.config` to `config` in the previous PRs https://github.com/XENONnT/WFSim/pull/94 and https://github.com/XENONnT/WFSim/pull/83.

### CODE REVIEW

**Comment by HenningSE** [comment]
Trying to run this branch in a notebook on dali. Looks like there is at least one other problem we/I have to fix before it works fine.

**Comment by HenningSE** [comment]
Got this error message linking to https://github.com/XENONnT/WFSim/blob/Fix_get_n_photons/wfsim/core.py#L59-L61. 
WFsim_error_NoneType
Don't know at the moment how to solve it.

**Comment by petergaemers** [comment]
Hi Henning can you explain what you're trying to do?
Because this is not related to https://github.com/XENONnT/WFSim/pull/94 or https://github.com/XENONnT/WFSim/pull/83

**Comment by petergaemers** [comment]
Hi Henning, thanks.
The error you're getting is that you're trying to simulate 0 photons. What are you doing to get this?

**Comment by HenningSE** [comment]
I'm using different instructions files generated with EPIX and then run WFsim. Checked the instructions file and `amp` is always larger 0. Could this be something like afterpulses?

**Comment by HenningSE** [comment]
With the last commit i changed the return of `photon_timings` in case of 0 photons from nothing to an empty numpy array.  Now the previously reported error is gone and the simulation seems to work fine. I'm not 100% that this "fix" is right so it would be great if someone more familiar with the code can check. 

I think we did not have this problem before since a empty array was set: `self._photon_timings = np.array([])` in S1 `__call__`. (Don't know how to properly link it so here is a screenshot from https://github.com/XENONnT/WFSim/pull/83:
WFsim_PR_missing_empty_array

**Pull request merged**
