### PR TITLE
maybe fixing chunking issue

### PR DESCRIPTION
**Pull request by zhut19**
**What is the problem / what does the code in this PR do**
Like the name of this pr

### CODE REVIEW

**Comment by petergaemers** [comment]
I was looking at the same place :P #119

**Comment by terliuk** [comment]
i will try to have a look today. It is a bit tricky to be sure that it doesn't happen again, as there is about 3-5 jobs out of 100 that fail due to this.

**Comment by zhut19** [comment]
@terliuk now I don't think this pr is ready, one of the tests failed due to that a chunk is created before the previous one end :(.

**Comment by zhut19** [comment]
@terliuk are you still available for a quick review? I tried with ~100 random seeds, those two changes are the only issue I catch.

**Pull request merged**
