### PR TITLE
Add n_pe to truth

### PR DESCRIPTION
**Pull request by petergaemers**
Right now the n_photons field in the truth is the number of detected photons + double pe emission.
This PR changes that to have n_photons be the number of detected photons and n_pe for the number of detected photo electrons (so photons+dpe)

### CODE REVIEW

**Comment by JoranAngevaare** [comment]
@petergaemers , this is super useful! Would you think we could also add a small field for the number of photons actually passing the DAQ-thresholds, as in the number of "truely" registered hits?

**Comment by ershockley** [comment]
@petergaemers thanks for this! Can we also save the true sampled gain values?

**Comment by petergaemers** [comment]
Hi guys, I'm sorry I completly missed these comments.

First for Jorans we don't have a number of photons passing the threshold, we have a current which is a bunch of them.

And for Evans point: maybe but it will not be straightforward at all. The main point is straxs fixed length arrays you need to set in advance

**Comment by JoranAngevaare** [comment]
@petergaemers do you think it would make sense to remove the `exclude_dpe_in_truth` option all-together from WFSim after this change?

**Comment by petergaemers** [comment]
Yes I do

**Pull request merged**
