### PR TITLE
Optical nv prototype

### PR DESCRIPTION
**Pull request by mzks**
Dear experts,

As I mentioned in slack channel and telecon, nVeto simulator is ready to work on our environment.
I added a plugin to use optical simulation.
I replaced hard-coded lines for TPC parameters to lines which use config parameters.
And I fix few bugs or something strange, I'm not 100% sure of these fixes.
The current branch has been worked our strax environment.
Some important features have not implemented yet, but before going ahead, I would like to recieve a review to confirm that I didn't break important part of wfsim.

### CODE REVIEW

**Comment by mzks** [comment]
This is notebook. https://xe1t-wiki.lngs.infn.it/doku.php?id=xenon:xenonnt:analysis:mc-subgroup:optical_nv_prototype1

**Comment by petergaemers** [comment]
Hi Keita, can you make sure your branch is up to date with master? Right now it's behind so this will make a mess

**Comment by mzks** [comment]
I resolved conflicts.

**Comment by jorana** [comment]
Hi Keita, I just removed myself from the reviewers as Peter and Tianyu are the absolute maintainers of this package. The only thing I would ask for is also adding a simple nVeto test to:
https://github.com/XENONnT/WFSim/blob/1dfc4dab319289d28c40871230582dcf9156ebdc/tests/test_wfsim.py

Should be easy to implement given the examples there.

**Comment by petergaemers** [comment]
This is no longer relevent.  See https://github.com/XENONnT/WFSim/pull/72

**Pull request closed without merging**
