### PR TITLE
reinstate tests

### PR DESCRIPTION
**Pull request by jorana**
Reinstate some tests. 

Perhaps from breaking this again in the future, I think adding a default config would help. For example, the xenon1t fax file is missing some configs, see the TODOs. It should be doable to test without access to the private files, most things are just a bunch of numbers in the end (ok, some pattern maps etc complicate things a bit).

### CODE REVIEW

**Comment by petergaemers** [comment]
Thanks Joran

**Comment by jorana** [comment]
OK, #83 broke the tests again...

**Comment by jorana** [comment]
ok so apart from the TODO's the test is now really failing due to errors induced in #83, all the more showing the need for testing

**Comment by petergaemers** [comment]
Should be fixed in https://github.com/XENONnT/WFSim/pull/91

**Pull request merged**
